### PR TITLE
Started because I wanted settable attributes *

### PR DESCRIPTION
**Pull request by alexdresko**
I have a project where I think I can use GutenTag. And, for the life of me, I can't find anything else like it. I still think it's one of the raddest libraries out there. Dunno who it's not a hit. Anyway, I had a requirement that attributes be settable.. so...

```
[TestMethod]
public void AttributeIsChanged()
{
    var tag = new Tag("div")
    {
        {"class", "foo"}
    };

    tag["class"] = "bar";

    Assert.AreEqual("bar", tag["class"]);
}
```

* Wrote a test to verify settable attributes. See the bottom of `WhenTag.cs`
* Basically merged the portable and web projects into one fancy .NET Standard 2.0 project.
* Solution wide R# code cleanup.
* I started going through R#'s "code issues in solution"... there are quite a few that I consider concerning, but I don't have time to fix. Mostly, I just want to revive this thing for now and will look to refine as I move forward with my other project.
* Switch the tests to MSTest v2 because, well, that's what I have installed and working. :)

### CODE REVIEW

**Comment by alexdresko** [comment]
Would be rad if you could also push this to nuget.

**Comment by alexdresko** [comment]
Rad, thanks. I do have another PR coming soon. If you're feeling especially trustworthy, make me a maintainer and I'll help setup an appveyor build to push new releases out to nuget automatically.

**Comment by kodefuguru** [comment]
No problem. Considering my current life situation, I probably won't be able to work on this for some time. Let me know if you need anything.

________________________________

**Comment by alexdresko** [comment]
Totes rad. I've almost got the appveyor build running. Can you your nuget API key to me@<my name>.com (or FB it to me)? You can get the key from https://www.nuget.org/account/ApiKeys

**Pull request merged**
